CLASS zcl_keyword DEFINITION PUBLIC.
  PUBLIC SECTION.
    METHODS run RETURNING VALUE(res) TYPE i.
ENDCLASS.

CLASS zcl_keyword IMPLEMENTATION.

  METHOD run.
    DATA case TYPE i.
  ENDMETHOD.

ENDCLASS.